version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "swimmwatch"
    target-branch: "dev"
    labels:
      - "pip-dependencies"
  - package-ecosystem: "github-actions"
    assignees:
      - "swimmwatch"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - "github-actions-dependencies"
