templateDir: "/local/custom-template"
packageName: "python_opendota"
projectName: "python-opendota"
gitRepoId: "python-opendota"
gitUserId: "swimmwatch"
packageUrl: "https://pypi.org/project/python-opendota/"
files:
  pyproject.hbs:
    templateType: SupportingFiles
    destinationFilename: pyproject.toml
  flake8.hbs:
    templateType: SupportingFiles
    destinationFilename: .flake8