# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.   # noqa: E501

    The version of the OpenAPI document: 19.0.0
    Generated by: https://openapi-generator.tech
"""

from python_opendota.paths.players_account_id_counts.get import (
    PlayersAccountIdCountsGet,
)
from python_opendota.paths.players_account_id.get import PlayersAccountIdGet
from python_opendota.paths.players_account_id_heroes.get import (
    PlayersAccountIdHeroesGet,
)
from python_opendota.paths.players_account_id_histograms_field.get import (
    PlayersAccountIdHistogramsFieldGet,
)
from python_opendota.paths.players_account_id_matches.get import (
    PlayersAccountIdMatchesGet,
)
from python_opendota.paths.players_account_id_peers.get import PlayersAccountIdPeersGet
from python_opendota.paths.players_account_id_pros.get import PlayersAccountIdProsGet
from python_opendota.paths.players_account_id_rankings.get import (
    PlayersAccountIdRankingsGet,
)
from python_opendota.paths.players_account_id_ratings.get import (
    PlayersAccountIdRatingsGet,
)
from python_opendota.paths.players_account_id_recent_matches.get import (
    PlayersAccountIdRecentMatchesGet,
)
from python_opendota.paths.players_account_id_refresh.post import (
    PlayersAccountIdRefreshPost,
)
from python_opendota.paths.players_account_id_totals.get import (
    PlayersAccountIdTotalsGet,
)
from python_opendota.paths.players_account_id_wardmap.get import (
    PlayersAccountIdWardmapGet,
)
from python_opendota.paths.players_account_id_wl.get import PlayersAccountIdWlGet
from python_opendota.paths.players_account_id_wordcloud.get import (
    PlayersAccountIdWordcloudGet,
)


class PlayersApi(
    PlayersAccountIdCountsGet,
    PlayersAccountIdGet,
    PlayersAccountIdHeroesGet,
    PlayersAccountIdHistogramsFieldGet,
    PlayersAccountIdMatchesGet,
    PlayersAccountIdPeersGet,
    PlayersAccountIdProsGet,
    PlayersAccountIdRankingsGet,
    PlayersAccountIdRatingsGet,
    PlayersAccountIdRecentMatchesGet,
    PlayersAccountIdRefreshPost,
    PlayersAccountIdTotalsGet,
    PlayersAccountIdWardmapGet,
    PlayersAccountIdWlGet,
    PlayersAccountIdWordcloudGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
