# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.   # noqa: E501

    The version of the OpenAPI document: 19.0.0
    Generated by: https://openapi-generator.tech
"""

from python_opendota.paths.teams.get import TeamsGet
from python_opendota.paths.teams_team_id.get import TeamsTeamIdGet
from python_opendota.paths.teams_team_id_heroes.get import TeamsTeamIdHeroesGet
from python_opendota.paths.teams_team_id_matches.get import TeamsTeamIdMatchesGet
from python_opendota.paths.teams_team_id_players.get import TeamsTeamIdPlayersGet


class TeamsApi(
    TeamsGet,
    TeamsTeamIdGet,
    TeamsTeamIdHeroesGet,
    TeamsTeamIdMatchesGet,
    TeamsTeamIdPlayersGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
