name: "Get updated package version"
description: "Generate appropriate new package version by current version and updated state."

inputs:
  curr-package-version:
    required: true
    description: "Current package version"
  updated-state:
    required: true
    description: "Updated state (got from openapi-diff tool)"

outputs:
  new-package-version:
    description: "New package version"
    value: ${{steps.gen-new-version.outputs.new_package_version}}

runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: "Install dependencies"
      run: pip install -r utils/requirements.txt
      shell: bash
    - name: "Run script"
      id: gen-new-version
      run: |
        new_package_version=$(python utils/update_package_version.py \ 
          --curr-version "${{inputs.curr-package-version}}" \
          --updated-state "${{inputs.updated-state}}"
        )
        echo "::set-output name=new_package_version::$new_package_version"
      shell: bash