name: "Create PR if OpenDota API has been updated"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  diff-spec:
    name: "Find difference between downloaded specification and current"
    runs-on: ubuntu-latest
    outputs:
      state: ${{steps.compare_state.outputs.state}}
      markdown-changes: ${{steps.markdown_changes.outputs.content}}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Download new OpenDota API spec"
        run: wget https://api.opendota.com/api --output-document spec.json
      - name: "Convert downloaded spec to v3"
        run: |
          curl --request POST \
               --data @spec.json \
               --header 'Content-Type: application/json' \
               'https://converter.swagger.io/api/convert' \
                --output spec.json
        shell: bash
      - name: "Compare downloaded specification and current"
        uses: swimmwatch/openapi-diff-action@v1.0.1
        id: compare_state
        with:
          old-spec: ".openapi-generator/spec.json"
          new-spec: "spec.json"
          markdown: "changes.md"
      - name: "Read changes.md file"
        id: markdown_changes
        uses: juliangruber/read-file-action@v1
        with:
          path: "changes.md"
      - name: "Upload downloaded specification for next job"
        uses: actions/upload-artifact@v3
        with:
          name: "downloaded_spec"
          path: "spec.json"
  create-pr:
    name: "Create PR"
    runs-on: ubuntu-latest
    needs:
      - diff-spec
    if: needs.diff-spec.outputs.state != 'no_changes'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Get downloaded specification from 'diff-spec' job"
        uses: actions/download-artifact@v3
        with:
          name: "downloaded_spec"
      - name: "Update old specification file"
        run: mv spec.json .openapi-generator/spec.json
      - name: 'Get previous tag'
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
      - name: "Detect appropriate new package version"
        uses: swimmwatch/openapi-diff-semver-bump@v1.0.1
        id: updated-version
        with:
          package-version: ${{ steps.get-latest-tag.outputs.tag }}
          updated-state: ${{ needs.diff-spec.outputs.state }}
      - name: "Generate SDK"
        uses: ./.github/actions/generate-sdk
        with:
          package-version: ${{ steps.updated-version.outputs.new-package-version }}
          spec-path: ".openapi-generator/spec.json"
      - name: "Create PR"
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          base: "dev"
          branch: "update-v${{steps.update-version.outputs.new-package-version}}"
          title: "Update package v${{steps.update-version.outputs.new-package-version}}"
          labels: |
            enhancement
          body: ${{needs.diff-spec.outputs.markdown-changes}}
          assignees: "swimmwatch"
          committer: "GitHub <noreply@github.com>"