name: "Release and deploy package to PyPI"

on:
  release:
    types:
      - created

jobs:
  deploy:
    name: "Build and deploy to PyPI"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v4
      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: "1.1.12"
      - name: "Build package"
        run: poetry build
      - name: "Publish package"
        run: poetry publish -u __token__ -p ${{secrets.PYPI_TOKEN}}
